export const dadosConsulta =
   [
      {
         "Produto": "66397 - FRONHA 50X70 MALHA LISA HAVAN CASA",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.1.1.2.1.4 - FRONHA AVULSA MALHA",
         "Perdas": 0,
         "Quantidade": 0,
         "PerdasAnterior": 5.13,
         "QuantidadeAnterior": 1,
         "ComparacaoValor": 5.13,
         "ComparacaoQuantidade": 1,
         "Id": 0
      },
      {
         "Produto": "98262 - JG CAMA CASAL 138X188X30 3PCS MALHA HAVAN CASA",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.1.2.3.1.4.2 - JG. CASAL MALHA",
         "Perdas": 30.56,
         "Quantidade": 1,
         "PerdasAnterior": 30.56,
         "QuantidadeAnterior": 1,
         "ComparacaoValor": 61.12,
         "ComparacaoQuantidade": 2,
         "Id": 1
      },
      {
         "Produto": "98265 - JG CAMA KING 193X203X35 3PCS MALHA HAVAN CASA",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.1.2.5.1.4.2 - JG. KING MALHA",
         "Perdas": 0,
         "Quantidade": 0,
         "PerdasAnterior": 37.31,
         "QuantidadeAnterior": 1,
         "ComparacaoValor": 37.31,
         "ComparacaoQuantidade": 1,
         "Id": 2
      },
      {
         "Produto": "128184 - PISO SOFISTICATA 50X75CM HAVAN",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.3.1.1.3.1 - TOALHA PISO BASICA",
         "Perdas": 0,
         "Quantidade": 0,
         "PerdasAnterior": -90.27,
         "QuantidadeAnterior": -12,
         "ComparacaoValor": -90.27,
         "ComparacaoQuantidade": -12,
         "Id": 3
      },
      {
         "Produto": "211006 - JG CAMA KING 193X203X35 3PCS MALHA SOLECASA",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.1.2.5.2 - JOGO CAMA KING ROLINHO",
         "Perdas": 28.17,
         "Quantidade": 1,
         "PerdasAnterior": 28.17,
         "QuantidadeAnterior": 1,
         "ComparacaoValor": 56.34,
         "ComparacaoQuantidade": 2,
         "Id": 4
      },
      {
         "Produto": "221119 - TOALHA DE MESA 140X140 LEPPER",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.2.1.2.1.2.1 - TOALHA QUADRADA 140 X 140",
         "Perdas": 42.48,
         "Quantidade": 3,
         "PerdasAnterior": 42.48,
         "QuantidadeAnterior": 3,
         "ComparacaoValor": 84.96,
         "ComparacaoQuantidade": 6,
         "Id": 5
      },
      {
         "Produto": "223507 - ROUPAO INFANTIL P MICROFIBRA",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.3.3.2.1.3 - ESTAMPADO",
         "Perdas": 0,
         "Quantidade": 0,
         "PerdasAnterior": 19.98,
         "QuantidadeAnterior": 1,
         "ComparacaoValor": 19.98,
         "ComparacaoQuantidade": 1,
         "Id": 6
      },
      {
         "Produto": "226857 - CENTRO MESA 78X78 DOHLER CLEAN",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.2.2.3.1.1 - CENTRO DE MESA",
         "Perdas": 5.59,
         "Quantidade": 1,
         "PerdasAnterior": 0,
         "QuantidadeAnterior": 0,
         "ComparacaoValor": 5.59,
         "ComparacaoQuantidade": 1,
         "Id": 7
      },
      {
         "Produto": "226925 - FRONHA 50X70 MICROFIBRA KIDS ESTAMPADA",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.1.15.1 - FRONHA KIDS",
         "Perdas": 0,
         "Quantidade": 0,
         "PerdasAnterior": 4.09,
         "QuantidadeAnterior": 1,
         "ComparacaoValor": 4.09,
         "ComparacaoQuantidade": 1,
         "Id": 8
      },
      {
         "Produto": "227809 - LENCOL QUEEN 158X198X28 LISO MICROFIBRA",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.1.1.1.4.1 - LENCOL QUEEN MICROFIBRA",
         "Perdas": 18.34,
         "Quantidade": 1,
         "PerdasAnterior": 0,
         "QuantidadeAnterior": 0,
         "ComparacaoValor": 18.34,
         "ComparacaoQuantidade": 1,
         "Id": 9
      },
      {
         "Produto": "227813 - FRONHA 50X70 MICROFIBRA LISA SOLECASA",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.1.1.2.1.1 - FRONHA AVULSA MICROFIBRA",
         "Perdas": 0,
         "Quantidade": 0,
         "PerdasAnterior": 16.68,
         "QuantidadeAnterior": 4,
         "ComparacaoValor": 16.68,
         "ComparacaoQuantidade": 4,
         "Id": 10
      },
      {
         "Produto": "228283 - PORTA TRAVESSEIRO 55X80 PLUSH HAVAN",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.1.1.4.1.5 - PORTA TRAVESSEIRO PLUSH",
         "Perdas": 12.53,
         "Quantidade": 1,
         "PerdasAnterior": 12.53,
         "QuantidadeAnterior": 1,
         "ComparacaoValor": 25.06,
         "ComparacaoQuantidade": 2,
         "Id": 11
      },
      {
         "Produto": "241887 - COBERTOR KING 240X260 PATRICIA FOSTER HAVAN",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.1.7.4.2.1 - COBERTOR KING LISO",
         "Perdas": 0,
         "Quantidade": 0,
         "PerdasAnterior": 55.42,
         "QuantidadeAnterior": 1,
         "ComparacaoValor": 55.42,
         "ComparacaoQuantidade": 1,
         "Id": 12
      },
      {
         "Produto": "265586 - FRONHA 50X90 KING BUONA FORTUNA",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.1.1.2.1.5.2 - FRONHA AVULSA 100% ALGODÃO",
         "Perdas": 0,
         "Quantidade": 0,
         "PerdasAnterior": 56.04,
         "QuantidadeAnterior": 4,
         "ComparacaoValor": 56.04,
         "ComparacaoQuantidade": 4,
         "Id": 13
      },
      {
         "Produto": "280821 - SOUSPLAT COLONIAL HAVAN",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.2.7 - SOUSPLAT",
         "Perdas": 0,
         "Quantidade": 0,
         "PerdasAnterior": 5.86,
         "QuantidadeAnterior": 1,
         "ComparacaoValor": 5.86,
         "ComparacaoQuantidade": 1,
         "Id": 14
      },
      {
         "Produto": "287076 - FRONHA 50X70 PLUSH ESTAMPADA HAVAN",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.1.1.2.1.6 - FRONHA AVULSA PLUSH",
         "Perdas": 17.24,
         "Quantidade": 2,
         "PerdasAnterior": 0,
         "QuantidadeAnterior": 0,
         "ComparacaoValor": 17.24,
         "ComparacaoQuantidade": 2,
         "Id": 15
      },
      {
         "Produto": "296375 - COBERTOR CASAL DOBBY 180X220 FPASSOS",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.1.7.2.2.1 - COBERTOR CASAL LISO",
         "Perdas": 95.1,
         "Quantidade": 3,
         "PerdasAnterior": 63.4,
         "QuantidadeAnterior": 2,
         "ComparacaoValor": 158.5,
         "ComparacaoQuantidade": 5,
         "Id": 16
      },
      {
         "Produto": "296377 - COBERTOR QUEEN DOBBY 220X240 FPASSOS",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.1.7.3.2.1 - COBERTOR QUEEN LISO",
         "Perdas": 42.8,
         "Quantidade": 1,
         "PerdasAnterior": 0,
         "QuantidadeAnterior": 0,
         "ComparacaoValor": 42.8,
         "ComparacaoQuantidade": 1,
         "Id": 17
      },
      {
         "Produto": "296378 - COBERTOR KING DOBBY 240X260 FPASSOS",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.1.7.4.2.1 - COBERTOR KING LISO",
         "Perdas": 50.03,
         "Quantidade": 1,
         "PerdasAnterior": 0,
         "QuantidadeAnterior": 0,
         "ComparacaoValor": 50.03,
         "ComparacaoQuantidade": 1,
         "Id": 18
      },
      {
         "Produto": "303904 - EDREDOM QUEEN 240X260 BUONA FORTUNA",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.1.5.3.1.5.2.2 - EDREDOM QUEEN 200 FIOS",
         "Perdas": 0,
         "Quantidade": 0,
         "PerdasAnterior": 127.54,
         "QuantidadeAnterior": 1,
         "ComparacaoValor": 127.54,
         "ComparacaoQuantidade": 1,
         "Id": 19
      },
      {
         "Produto": "303972 - FRONHA 50X70 BUONA FORTUNA",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.1.1.2.1.5.2 - FRONHA AVULSA 100% ALGODÃO",
         "Perdas": 0,
         "Quantidade": 0,
         "PerdasAnterior": 24.61,
         "QuantidadeAnterior": 2,
         "ComparacaoValor": 24.61,
         "ComparacaoQuantidade": 2,
         "Id": 20
      },
      {
         "Produto": "305074 - PISO 50X65 ATOALHADO HAVAN",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.3.1.1.3.1 - TOALHA PISO BASICA",
         "Perdas": 11.21,
         "Quantidade": 2,
         "PerdasAnterior": 28.02,
         "QuantidadeAnterior": 5,
         "ComparacaoValor": 39.23,
         "ComparacaoQuantidade": 7,
         "Id": 21
      },
      {
         "Produto": "310466 - PANO DE COPA NATAL LEPPER",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.2.6.1.1.3 - NATAL - PANO DE COPA",
         "Perdas": 0,
         "Quantidade": 0,
         "PerdasAnterior": 2.63,
         "QuantidadeAnterior": 1,
         "ComparacaoValor": 2.63,
         "ComparacaoQuantidade": 1,
         "Id": 22
      },
      {
         "Produto": "322122 - PORTA TRAVESSEIRO 55X80 MICROFIBRA SOLECASA",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.1.1.4.1.1 - PORTA TRAVESSEIRO MICROFIBRA",
         "Perdas": 0,
         "Quantidade": 0,
         "PerdasAnterior": 7.84,
         "QuantidadeAnterior": 1,
         "ComparacaoValor": 7.84,
         "ComparacaoQuantidade": 1,
         "Id": 23
      },
      {
         "Produto": "332068 - KIT COLCHA QUEEN 240X260 3PCS LISA SOLECASA",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.1.3.3.1.1.1 - QUEEN MICROFIBRA LISA",
         "Perdas": 0,
         "Quantidade": 0,
         "PerdasAnterior": 58.59,
         "QuantidadeAnterior": 1,
         "ComparacaoValor": 58.59,
         "ComparacaoQuantidade": 1,
         "Id": 24
      },
      {
         "Produto": "333485 - KIT COLCHA CASAL 220X240 3PCS ESTAMP SOLECASA",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.1.3.2.1.1.2 - CASAL MICROFIBRA ESTAMPADA",
         "Perdas": 45.97,
         "Quantidade": 1,
         "PerdasAnterior": 45.97,
         "QuantidadeAnterior": 1,
         "ComparacaoValor": 91.94,
         "ComparacaoQuantidade": 2,
         "Id": 25
      },
      {
         "Produto": "333646 - SOUSPLAT GLASS",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.2.7 - SOUSPLAT",
         "Perdas": 6.52,
         "Quantidade": 1,
         "PerdasAnterior": 0,
         "QuantidadeAnterior": 0,
         "ComparacaoValor": 6.52,
         "ComparacaoQuantidade": 1,
         "Id": 26
      },
      {
         "Produto": "336774 - JG CAMA CASAL 138X188X30 3PCS MALHA SOLECASA",
         "Filial": "1 - BRUSQUE",
         "Familia": "1.1.2.3.2 - JOGO CAMA CASAL ROLINHO",
         "Perdas": 20.39,
         "Quantidade": 1,
         "PerdasAnterior": 20.39,
         "QuantidadeAnterior": 1,
         "ComparacaoValor": 40.78,
         "ComparacaoQuantidade": 2,
         "Id": 27
      },

   ]